# -*- coding: utf-8 -*-
"""Python Bootcamp - Upskill-day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/170NDgx5kqA8HEh31WjfSTPlB0ERNgNcc

Functions in Python

Types of Functions 
- Built-in-functions 
- User-Defined functions

Built-in-Functions -These functions are already written and defined by the python program
"""

#print(), min(), max()
print("Python")

min(1,2,3)

max(1,2,3)

mean({1},{2},{3})

"""User Defined Functions """

#write a functions to find sum of 2 numbers

def add(a,b):
  SUM = a + b
  print(SUM)
    
add(2,3)

"""Components of a function:
1. Parameters
2. Arguments
3. Return statement
"""

def hello(name):
  print("Hello" + name)

hello(" Suraj")

def subtraction(a,b):
  x = a - b
  print(x)

subtraction(10,5)

def subtraction():
  a = int(input())
  b = int(input())
  x = a - b
  print(x)

  subtraction()

def hello(name):
  print("Hello"+ name)

hello("Python")

def add(a,b):
  print(a+b)

add(3)

def add(a,b):
  print(a+b)

add(3,5)

"""return Statement"""

def hello():
  print("Hello World")
  return("Hello")

# Multiply the output of "hello()" with 2
hello() + "Suraj"

def hello_noreturn():
  print("Hello World")

# (Try to) multiply the output of "hello_noreturn()" with 2
hello_noreturn() * 2

def hello_noreturn():
  print("Hello World")
  return("Python")

language = hello_noreturn()

print(language)

#function immediately exits when they come accross a return statement, even if it means that they won't return any value

def example():
  for x in range(10):
    if x == 2:
      return
    print("Run!")

    example()

def add(a,b):
  SUM = a + b
  return(SUM, a)
  final_sum, a_value = add (5,10)
  print(final_sum, a_value)

def add(a,b):
  SUM = a + b
  return(SUM, a)
value = add(5,10)
print(value)

"""Docstring in Functions """

def hello():
"""Print "Hello World".

  Returns:
    None
    """

    print("Hello World")
    return:

"""Default Arguments"""

def hello(name="world"):
  print("Hello " + name)

hello()

def hello(name="world"):
  print("Hello " + name)

hello("Python")

def maximum(a,b,c=12):
  return max(a,b,c)

maximum(10,11)

def maximum(a,b=12,c):
  return max(a,b,c)

maximum(10,11,15)

def maximum(a,c,b=12):
  return max(a,b,c)

maximum(10,11)

"""Arguments :
1. Default Arguments 
2. Required Arguments
3. Key word Arguments 
"""

# Define 'pluse()' function
def pluse(a,b):
  print(b)
  return